from setuptools import setup, find_packages

setup(
    name="deepethos",
    version="0.1.0",
    author="AI Ethics Research Team",
    author_email="research@example.com",
    description="A framework for analyzing ethical reasoning across AI models from different providers",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/deepethos",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.7",
    install_requires=[
        "pandas>=1.3.0",
        "numpy>=1.20.0",
        "matplotlib>=3.4.0",
        "openai>=1.5.0",
        "anthropic>=0.5.0", 
        "google-generativeai>=0.3.0",
        "python-dotenv>=0.19.0",
        "tqdm>=4.62.0",
        "argparse>=1.4.0",
    ],
) 